<a href="https://colab.research.google.com/github/Ekram49/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Ekram_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The visible layer that interacts directly with the database to get inputs.
### Hidden Layer: Layers after the input layer that cannot be accessed directly.
### Output Layer: The layer that ouputs the results in a form suitable for the problem
### Neuron: A single node.
### Weight: The value that an input is multiplied by. A scaling factor between nodes
### Activation Function: The function that takes model results and converts them into a for that is suitable for the problem.
### Node Map: A topological map of a neural network detailing the nodes and their connections.
### Perceptron: The simplest form of neural network that simply takes an input and returns a weighted ouput


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

The neural net recieves inputs through the input node. The inputs are then sent into corresponding hidden nodes (one for each features) where weights are applied to them. Biases are added to the values and the results are passed into additional hidden layers if there are any. After the last hidden layer, the results are passed into an activation function which formats the results into a response that suits the problem (e.g. converting values to a range from 0,1 for probabilities). The results are then ouputted by the output layer.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
##### Your Code Here #####

df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
import numpy as np

In [0]:
inputs = np.array([
                   [0,0,1],
                   [1,0,1],
                   [0,1,1],
                   [1,1,0]
])

correct_outputs = [[1], [1], [1], [0]]

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
  sx = sigmoid(x)
  return sx * (1-sx)

In [6]:
weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.46775406],
       [ 0.0401636 ],
       [-0.47231814]])

In [0]:
weighted_sum = np.dot(inputs, weights)

In [8]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.38406772],
       [0.28088576],
       [0.39361196],
       [0.39470185]])

In [9]:
error = correct_outputs - activated_output
error

array([[ 0.61593228],
       [ 0.71911424],
       [ 0.60638804],
       [-0.39470185]])

In [10]:
adjustments = error * sigmoid_derivate(weighted_sum)
adjustments

array([[ 0.14570476],
       [ 0.14525313],
       [ 0.14473366],
       [-0.09429913]])

In [11]:
weights += np.dot(inputs.T, adjustments)
weights

array([[-0.41680006],
       [ 0.09059813],
       [-0.03662659]])

In [15]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    # Can add in learning rate for better performance.
    adjustments = error * sigmoid_derivate(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.41126533]
 [-2.40925153]
 [ 7.49031259]]
Output after training
[[0.9994418 ]
 [0.99381237]
 [0.99382474]
 [0.00799854]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [26]:
"""
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
# train test split

X = diabetes.drop('Outcome', axis=1)
y = diabetes['Outcome']

# fitting the data
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=feats)
X_scaled.head()
"""

"\nfrom sklearn.preprocessing import MinMaxScaler, Normalizer\n\nfeats = list(diabetes)[:-1]\n# train test split\n\nX = diabetes.drop('Outcome', axis=1)\ny = diabetes['Outcome']\n\n# fitting the data\nscaler = MinMaxScaler()\nX_scaled = pd.DataFrame(scaler.fit_transform(X), columns=feats)\nX_scaled.head()\n"

In [27]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

# Set the features as an array without the last column
features = list(diabetes)[:-1]

# Set the minmaxscalar
scaler = MinMaxScaler()

# Fit transform on the data with the set features
X = scaler.fit_transform(diabetes[features])

# Show the data
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [28]:
# Set the target with the last column (correct_outcome/y)
y = diabetes.iloc[:, 8].values

# Show the array
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [0]:
##### Update this Class #####


# perceptron class.
class Perceptron(object):
    
    def __init__(self, niter = 10000):
        self.niter = niter
    # sigmoid activation function.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    # sigmoid derivative function to update weights.
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
    # predict function.
    def predict(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # randomly initialize weights
        self.weight = np.zeros(X.shape[1])

        for i in range(self.niter):
            # sum up the weights.
            weighted_sum = np.dot(X, self.weight)  
            # use the sigmoid function on the weighted sum.
            activated_output = sigmoid(weighted_sum)   
            # find the calculation error.
            error = y - activated_output   
            # use the derivative function on the avivated outputs.
            adjustments = error * sigmoid_derivative(activated_output)   
            # update the weights with adjustments.
            self.weight += np.dot(X.T, adjustments)

        return activated_output


In [0]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        self.weight = np.zeros(1 + X.shape[1])
        self.inputs = X.values.tolist()
        self.outputs = y.values.tolist()

            # Weighted sum of inputs / weights

            # Activate!
            #activated_output = sigmoid(weighted_sum)

            # Cac error
            #error = correct_outputs - activated_output

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?